name: Upstream Changes PR

permissions: write-all

on: 
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Create Branch
        env:
          GITHUB_TOKEN: ${{ github.token }}
        uses: peterjgrainger/action-create-branch@v2.2.0
        with:
          branch: unmerged-upstream
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: unmerged-upstream
          fetch-depth: 0 
      - name: Merge Upstream
        id: merge
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git merge origin/main
          git remote add upstream https://github.com/glitch-soc/mastodon
          git fetch upstream
          git merge upstream/main
          changes=$(git push origin 2>&1)
          if [ "$changes" = "Everything up-to-date" ]; then
            echo "skip=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Check if PR exists
        env: 
          GH_TOKEN: ${{ github.token }}
        id: check
        run: |
          prs=$(gh pr list \
            --repo "$GITHUB_REPOSITORY" \
            --json baseRefName,headRefName \
            --jq '
              map(select(.baseRefName == "dev" and .headRefName == "unmerged-upstream"))
              | length
            ')
          if ((prs > 0)); then
            echo "skip=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Create Pull Request
        if: |
          !steps.check.outputs.skip &&
          !steps.merge.outputs.skip
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: 'Merge Upstream Changes',
              owner,
              repo,
              head: 'unmerged-upstream',
              base: 'main',
              body: 'This PR was *auto-generated* by the `Upstream Changes PR` action and contains unmerged changes from the upstream [glitch-soc](https://github.com/glitch-soc/mastodon) repository.'
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['upstream', 'automated pr']
            });
